In [27]:
import pandas as pd 
import csv

Tratando a planilha listings

In [ ]:
df = pd.read_csv(
    "data/listings.csv", #aqui voce deve colocar o caminho do arquivo que voce baixou
    sep=",",
    quotechar='"',
    encoding="utf-8",
    engine="python"
)

# remover quebras de linha internas
df = df.replace(r'\r\n|\r|\n', ' ', regex=True)

# remover vírgula do price (separador de milhar)
df["price"] = df["price"].replace('[\$,]', '', regex=True)

colunas_desejadas = [
    "id",
    "host_id",
    "neighbourhood_cleansed",
    "latitude",
    "longitude",
    "property_type",
    "room_type",
    "accommodates",
    "bathrooms",
    "bedrooms",
    "beds",
    "price",
    "minimum_nights",
    "maximum_nights",
    "number_of_reviews",
    "review_scores_rating",
    "availability_365"
]

df = df[colunas_desejadas]

df.to_csv(
    "data/listings_filtered.csv",
    index=False,
    encoding="utf-8",
    sep=",",
    quoting=csv.QUOTE_NONE,
    escapechar="\\"
)
print("Arquivo tratado corretamente.")

<>:13: SyntaxWarning: invalid escape sequence '\$'
<>:13: SyntaxWarning: invalid escape sequence '\$'
C:\Users\DSgomes\AppData\Local\Temp\ipykernel_13908\2271776289.py:13: SyntaxWarning: invalid escape sequence '\$'
  df["price"] = df["price"].replace('[\$,]', '', regex=True)

Arquivo tratado corretamente.

In [32]:
df = pd.read_csv("data/listings.csv")
df.head()

,id,listing_url,scrape_id,last_scraped,source,name,description,neighborhood_overview,picture_url,host_id,...,review_scores_communication,review_scores_location,review_scores_value,license,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
0,821198084644106078,https://www.airbnb.com/rooms/821198084644106078,20250926170004,2025-09-27,city scrape,Bright and Peaceful Leblon Loft,Welcome! Come relax in our bright and stylish ...,Beautiful tree lined street just 3 blocks from...,https://a0.muscache.com/pictures/hosting/Hosti...,84350716,...,4.94,4.99,4.85,NaN,f,1,1,0,0,2.72
1,821198370698658112,https://www.airbnb.com/rooms/821198370698658112,20250926170004,2025-09-27,city scrape,Copacabana 100% reformado.,Guarantee of a safe and quality stay! <br /><...,"Copacabana, in the part near the neighborhood ...",https://a0.muscache.com/pictures/miso/Hosting-...,4347269,...,NaN,NaN,NaN,NaN,f,2,2,0,0,NaN
2,821200521820144734,https://www.airbnb.com/rooms/821200521820144734,20250926170004,2025-09-26,city scrape,hambiente familia,Relax with the whole family in this quiet acco...,NaN,https://a0.muscache.com/pictures/7485ea61-a28a...,499903412,...,NaN,NaN,NaN,NaN,t,2,1,1,0,NaN
3,821213014263313420,https://www.airbnb.com/rooms/821213014263313420,20250926170004,2025-09-27,previous scrape,Amazing en suite bedroom Leblon,"Kick back and relax in this calm, stylish spac...",NaN,https://a0.muscache.com/pictures/miso/Hosting-...,449763717,...,5.00,5.00,4.67,NaN,f,2,1,1,0,0.10
4,821223043903573522,https://www.airbnb.com/rooms/821223043903573522,20250926170004,2025-09-27,city scrape,Incrível apartamento frente mar,Amazing 1-bedroom apartment facing the sea. Co...,NaN,https://a0.muscache.com/pictures/miso/Hosting-...,25961210,...,5.00,5.00,5.00,NaN,f,1,1,0,0,0.60

Tratando a planilha calendar

In [ ]:
df_c = pd.read_csv("data/calendar.csv") #aqui voce deve colocar o caminho do arquivo que voce baixou
df_c.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15719845 entries, 0 to 15719844
Data columns (total 7 columns):
 #   Column          Dtype
---  ------          -----
 0   listing_id      int64
 1   date            object
 2   available       object
 3   price           float64
 4   adjusted_price  float64
 5   minimum_nights  int64
 6   maximum_nights  int64
dtypes: float64(2), int64(3), object(2)
memory usage: 839.5+ MB

In [22]:
df_c.head()

,listing_id,date,available,price,adjusted_price,minimum_nights,maximum_nights
0,821198084644106078,2025-09-27,f,NaN,NaN,2,90
1,821198084644106078,2025-09-28,f,NaN,NaN,2,90
2,821198084644106078,2025-09-29,f,NaN,NaN,2,90
3,821198084644106078,2025-09-30,f,NaN,NaN,2,90
4,821198084644106078,2025-10-01,f,NaN,NaN,2,90

In [ ]:
df_c = pd.read_csv("data/calendar.csv",#aqui voce deve colocar o caminho do arquivo que voce baixou
                   sep=",",
                   quotechar='"',
                   encoding="utf-8",
                   engine="python")


df_c = df_c.replace(r'\r\n|\r|\n', ' ', regex=True)

colunas_desejadas = [
    "listing_id",
    "date",
    "available"
]

df_c = df_c[colunas_desejadas]


df_c.to_csv(
    "data/calendar_filtered.csv",
    index=False,
    encoding="utf-8",
    sep=",",
    quoting=csv.QUOTE_NONE,
    escapechar="\\"
)
print("Arquivo tratado corretamente.")

Arquivo tratado corretamente.

In [24]:
print(df_c.columns)

Index(['listing_id', 'date', 'available', 'price', 'adjusted_price',
       'minimum_nights', 'maximum_nights'],
      dtype='object')

Tratando a planilhas reviews

In [ ]:
df_r = pd.read_csv("data/reviews.csv")

df_r.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1127716 entries, 0 to 1127715
Data columns (total 6 columns):
 #   Column         Non-Null Count    Dtype
---  ------         --------------    -----
 0   listing_id     1127716 non-null  int64
 1   id             1127716 non-null  int64
 2   date           1127716 non-null  object
 3   reviewer_id    1127716 non-null  int64
 4   reviewer_name  1127714 non-null  object
 5   comments       1127680 non-null  object
dtypes: int64(3), object(3)
memory usage: 51.6+ MB

In [33]:
df_r = pd.read_csv("data/reviews.csv",
                   sep=",",
                   quotechar='"',
                   encoding="utf-8",
                   engine="python")


df_r = df_r.replace(r'\r\n|\r|\n', ' ', regex=True)

colunas_desejadas = [
    "listing_id",
    "date",
    "reviewer_id",
]

df_r = df_r[colunas_desejadas]


df_r.to_csv(
    "data/reviews_filtered.csv",
    index=False,
    encoding="utf-8",
    sep=",",
    quoting=csv.QUOTE_NONE,
    escapechar="\\"
)
print("Arquivo tratado corretamente.")

Arquivo tratado corretamente.

In [ ]:
df_r.info()